# Generated by Django 3.2.18 on 2023-03-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mograapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsmodel',
            name='date_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventsmodel',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
